<?php

declare(strict_types=1);

namespace Aether\Events;

/**
 * Fired when a quantum device produces entropy via
 * AbstractQuantumDriver::generateEntropy().
 *
 * Deliberately excludes the generated bytes. EntropyGenerator::generate(),
 * ::hex() and ::integer() feed straight into material a listener must not be
 * able to observe or replay (tokens, keys, nonces) — putting the value on an
 * event would let any registered listener, log channel or third-party
 * package see entropy meant to stay secret. Only the request's public
 * metadata (how many bits, from which driver) is exposed here; capture the
 * return value of EntropyGenerator directly if you need the material itself.
 */
final readonly class EntropyGenerated
{
    public function __construct(
        public string $driver,
        public int $bits,
    ) {}
}
