<?php

declare(strict_types=1);

namespace Aether\Events;

/**
 * Fired when a quantum device produces entropy via AbstractQuantumDriver::generateEntropy().
 *
 * Excludes generated bytes to prevent leaking sensitive entropy (tokens, keys, nonces) to listeners.
 */
final readonly class EntropyGenerated
{
    public function __construct(
        public string $driver,
        public int $bits,
    ) {}
}
